import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavSideBar from "./NavSideBar";
import { AuthProvider } from "@/context/AuthProvider";
import ProtectedRoute from "@/context/ProtectedRoutes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ProtectedRoute>
            <nav>
              <NavSideBar />
            </nav>
            <main className="ml-[15%] md:ml-[10%] lg:ml-[5%]">{children}</main>
          </ProtectedRoute>
        </AuthProvider>
      </body>
    </html>
  );
}
